export const AppRoute = {
  AUTH : 'Auth',
  SIGN_IN:'Sign In',
  SIGN_UP :'Sign Up',
  RESET_PASSWORD : 'Reset Passrord',
  HOME : 'HomeScreen',
  TODO : 'ToDo',
  TODO_IN_PROGRESS : 'ToDo In Progress',
  TODO_DONE : 'ToDo Done',
  TODO_DETAILS : 'ToDo Details',
  PROFILE : 'Profile',
  ABOUT : 'About',
  ADD_CAMERA: 'AddCamera',
  MEDIA: 'Media',
  MEDIA_DETAIL: 'MediaDetail',
  CAMERA_DETAIL: 'CameraDetails',
}
