export const AppRoute = {
    AUTH: 'Auth',
    SIGN_IN: 'Sign In',
    SIGN_IN_FORM: 'Sign In Form',
    SIGN_UP: 'Sign Up',
    SIGN_UP_FORM: 'Sign Up Form',
    RESET_PASSWORD: 'Reset Password',
    HOME: 'HomeScreen',
    TODO: 'ToDo',
    TODO_IN_PROGRESS: 'ToDo In Progress',
    TODO_DONE: 'ToDo Done',
    TODO_DETAILS: 'ToDo Details',
    CHANGE_PASS: 'ChangePassword',
    ABOUT: 'About',
    ADD_CAMERA: 'AddCamera',
    MEDIA: 'Media',
    MEDIA_DETAIL: 'MediaDetail',
    CAMERA_STREAM: 'Camera Live',
    CAMERA_DETAIL: 'CameraDetails',
    CAMERA_EDIT: 'Edit Camera Information',
    CAMERA_EDIT_MODE: 'Edit Camera Mode',
    SETTINGS: 'Settings',
    VIDEO_PLAYER_SCREEN: 'Video',
    PROFILE: 'Profile',
};
