module.exports = {
    Colors: {
        white: '#fff',
        black: '#000',
        screen: '#e7eefb',
        text: '#30302f',
        secondText: '#fff',
        alert: '#ff1b48',
        light: '#EEF2FE',
        purple_blue: '#22215B',
        light_purple_blue: '#5553cf',
        whisper: '#f5f5f9',
        pigeon_post: '#bcc4de',
        arapawa: '#140b72',
        violet: '#3f3499',
        cadet_blue: '#aba7c0',
        pomegranate: '#f44324',
        grey: '#524e51',
        brandy_rose: '#ba8393',
    },
};
